### ISSUE TITLE
Cluster structure is not set up for cluster: PistachiosCluster

### ISSUE THREAD

**Issue by mathslimin** [lyogavin/Pistachio#20]
org.apache.helix.HelixException: Cluster structure is not set up for cluster: PistachiosCluster
	at org.apache.helix.manager.zk.ZKHelixManager.handleNewSession(ZKHelixManager.java:793)
	at org.apache.helix.manager.zk.ZKHelixManager.createClient(ZKHelixManager.java:461)
	at org.apache.helix.manager.zk.ZKHelixManager.connect(ZKHelixManager.java:487)
	at com.yahoo.ads.pb.PistachiosServer.main(PistachiosServer.java:454)

my config
StorageEngine.Path=/home/pistachio/var/pistachiostore/store
StorageEngine.KC.RecordsPerPartition=2000000
StorageEngine.KC.MemoryPerPartition=640000000
Pistachio.offsetGapThreadHold=3000
Pistachio.Store.ThreadsPerPartition=4
Pistachio.NoMasterAutoRetry=True
Pistachio.ConnectionBrokenAutoRetry=True
Pistachio.AutoRetry.BackOff.InitialIntervalMillis=100
Pistachio.AutoRetry.BackOff.MaxElapsedTimeMillis=100000
Pistachio.AutoRetry.BackOff.MaxIntervalMillis=25000
#pistachio.partitioner=com.yahoo.ads.pb.ExamplePartitioner
Pistachio.DoNothing=false
Pistachio.Processor.JarPath=/home/pistachio/tmp/
Pistachio.Processor.ClassName=com.yahoo.ads.pb.ExampleEventProcessor

#Pistachio.ZooKeeper.Server=mbus0001.pbp.bf1.yahoo.com:2181,mbus0002.pbp.bf1.yahoo.com:2181,mbus0003.pbp.bf1.yahoo.com:2181,mbus0004.pbp.bf1.yahoo.com:2181,mbus0005.pbp.bf1.yahoo.com:2181
Pistachio.ZooKeeper.Server=localhost:2181
Profile.Kafka.TopicPrefix=PistachiosPartition.
#Kafka.Broker=kafka0001.pbp.bf1.yahoo.com:4443,kafka0002.pbp.bf1.yahoo.com:4443,kafka0003.pbp.bf1.yahoo.com:4443,kafka0004.pbp.bf1.yahoo.com:4443,kafka0005.pbp.bf1.yahoo.com:4443,kafka0006.pbp.bf1.yahoo.com:4443,kafka0007.pbp.bf1.yahoo.com:4443,kafka0008.pbp.bf1.yahoo.com:4443,kafka0009.pbp.bf1.yahoo.com:4443,kafka00010.pbp.bf1.yahoo.com:4443
Kafka.Broker=localhost:4443
kafka.soTimeout=30000
kafka.bufferSize=65536
kafka.request.required.ack=1
kafka.queue.buffering.max.ms=100
kafka.producer.type=async

Network.Netty.Port=9091
Network.Netty.BossThreads=1
Network.Netty.WorkerThreads=30
Network.Netty.ClientConnectionTimeoutMillis=10000
Network.Netty.ClientReadTimeoutMillis=10000
Network.Netty.ServerReadTimeoutMillis=10000

**Comment by akki** [comment]
@mathslimin 
This looks like a super-old issue but do you remember how you solved it?
